version: '3.1'

services:
  db:
    image: postgres:12.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master
    volumes:
      - ./db/1_dump.sql:/docker-entrypoint-initdb.d/1_init.sql
#      - ./db/2_pgsql.admin.sql:/docker-entrypoint-initdb.d/2_admin.sql
#      - ./db/3_master_public_goadmin_menu.sql:/docker-entrypoint-initdb.d/3_master_public_goadmin_menu.sql
